sudo: required
dist: trusty
language: node_js
node_js:
- 6

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

before_script:
- ng build
- npm install angular-cli-ghpages --save-dev


after_success:
- ng github-pages:deploy

cache:
directories: node_modules

# safelist
branches:
only:
- master
